---
title: "Center Level Statistics"
format:
  html:
    code-fold: true
    code-summary: "Show the code"
    self-contained: true
execute:
  echo: false
    
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  echo = FALSE,
  out.width = "60%", fig.width=8, fig.height=6,
  message = FALSE, warning = FALSE,
  # attr.output='style="max-height: 50px;"', # vertical scroll box
  skimr_include_summary = FALSE
)
options(knitr.kable.NA = '') # set missing table values to blank
options(width = 90)
theme_set(theme_bw())
```

```{r utils, echo=FALSE, message=FALSE, warning=FALSE}
#: round number to specific number of decimal places
digits <- function(x, k=2) formatC(x, digits=k, format="f")

#: print table
library(kableExtra)
print_table <- function(x, digits=3, align="r", position = "left"){
  kbl(x, align = align, digits=digits) %>% 
  row_spec(0, align="c") %>% 
  kable_styling(full_width = FALSE, position = position,
                bootstrap_options = c("striped", "hover","responsive")) %>% 
    scroll_box(width = "90%", height = "300px")
}
```

```{r load-all, include = FALSE, cache = TRUE}
#----------------------------------------------------------------------------#
## Load Packages ----
#----------------------------------------------------------------------------#
library(tidyverse)

#----------------------------------------------------------------------------#
## Load Data ----
#----------------------------------------------------------------------------#

dir_data = "data"
PTR_all = read_rds(file.path(dir_data, "PTR.rds"))
WL_hist = read_rds(file.path(dir_data, "cand_wl_hist.rds"))

#----------------------------------------------------------------------------#
## Add waitlist information ----
#----------------------------------------------------------------------------#

#: Get waitlist status and waitlist organ at time of match run
WL_STATUS = PTR_all %>% select(PTR_ID, WL_ID_CODE, MATCH_SUBMIT_DT) %>% 
  left_join(WL_hist, by="WL_ID_CODE") %>% 
  filter(CHG_DT < MATCH_SUBMIT_DT) %>% 
  group_by(PTR_ID) %>% 
    slice_max(CHG_DT, with_ties = FALSE) %>% 
  ungroup() %>% 
  select(PTR_ID, ORG_CAND = ORG, STATUS_CAND = STATUS)

#: get date candidate added to waitlist
#   This should match thoracic$INIT_DATE.
#   there are only a handful of cases where INIT_DATE < WL_DATE (mostly  < 2004)
cand_listed_date = WL_hist %>%
  filter(CHG_TY == "A") %>%          # date activated on waitlist
  distinct() %>%
  transmute(WL_ID_CODE, WL_DATE = as.Date(CHG_DT))

#: add data to PTR 
PTR = PTR_all %>% 
  # add PT_CODE, ORG_CAND, and STATUS_CAND to PTR
  left_join(WL_STATUS, by="PTR_ID") %>%  
  # add data candidate placed on waitlist
  left_join(cand_listed_date, by = "WL_ID_CODE")  # left_join(thoracic, by = "WL_ID_CODE") 

#----------------------------------------------------------------------------#
## Make offer data ----
#  NOTES: 
#   - ONLY offers from DONORS < 30 years old are included! 
#   - Candidates < 18; on HR waitlist (not HL)
#   - Candidates added to waitlist between 2010 and 2019
#   - Our offer data is from 2010-march 2021, so there will be some
#     candidates still on waitlist at march 2021. 
#----------------------------------------------------------------------------#

offers = PTR %>% 
  # add year and if offered donor was eventually utilized
  mutate(
    MATCH_RUN_YEAR = format(MATCH_SUBMIT_DT, "%Y"),
    donor_utilized = ifelse(is.na(MAX_ACCEPT_SEQ), 0, 1)
  ) %>% 
  # get population of interest
  filter(
    AGE_PT < 18,        # Pediatric Candidate
    ORG_CAND == "HR",   # Candidate only on HR waitlist (not HL)
    WL_DATE >= as.Date("2010-01-01"), # listed after 2010 (so we have offer data)
    WL_DATE <= as.Date("2019-12-31"), # listed before 2020
  ) 

```

## Time until first offer

```{r}
#----------------------------------------------------------------------------#
## Time until first offer ----
#----------------------------------------------------------------------------#

#: calculate time to first offer
#  Notes:
#   - Using days between waitlist registration and match run.
#     Could use time at initial response, which may change by a day or two
#     but there are also some large outliers. 

first_offer = offers %>% 
  select(WL_ID_CODE, STATUS_CAND, WL_DATE, LISTING_CTR_CODE, 
         MATCH_SUBMIT_DT, INITIAL_RESPONSE_DT, 
         PTR_SEQUENCE_NUM) %>% 
  arrange(MATCH_SUBMIT_DT, INITIAL_RESPONSE_DT) %>% 
  slice(1, .by = WL_ID_CODE) %>% 
  mutate(
    wait_days = as.numeric(as.Date(MATCH_SUBMIT_DT) - WL_DATE)
  ) %>% 
  transmute(
    LISTING_CTR_CODE, 
    WL_ID_CODE, STATUS_CAND, 
    YR = format(MATCH_SUBMIT_DT, "%Y"), 
    wait_days
  )

#: summarize first offer waiting time by listing center

waiting_time = left_join(
  first_offer %>% 
    group_by(LISTING_CTR_CODE) %>% 
      summarize(
        n_total = n(),
        median_wait_days = median(wait_days)
      ) %>% 
    ungroup(), 
  
  first_offer %>% 
    group_by(LISTING_CTR_CODE, STATUS_CAND) %>% 
      summarize(
        n = n(),
        median_wait_days = median(wait_days)
      ) %>% 
      mutate(p = n/sum(n)) %>% 
    ungroup() %>% 
    complete(LISTING_CTR_CODE, STATUS_CAND, fill = list(n = 0L, p = 0)) %>% 
    mutate(STATUS_CAND = str_remove(STATUS_CAND, "Status ")) %>% 
    pivot_wider(
      names_from = c(STATUS_CAND), 
      values_from = c(n, p, median_wait_days), 
    )
)
```


```{r}
waiting_time %>% print_table()
waiting_time %>% write_csv("data/waiting_time.csv")
# n_total: total number of candidates at center
# n_{1A, 1B, 2}: number of candidates at each status
# p_{1A, 1B, 2}: proportion of candidates at each status
# median_wait_days: overall median number of days until first offer
# median_wait_days_{1A, 1B, 2}: median number of days until first offer (for status)
```

## Calculate Listing Center Refusal statistics

```{r}

#----------------------------------------------------------------------------#
## Calculate Listing Center Refusal statistics ----
#----------------------------------------------------------------------------#

refusals = offers %>% 
  group_by(WL_ID_CODE, LISTING_CTR_CODE) %>% 
    summarize(
      n_offers = n_distinct(DONOR_ID),
      accept = any(OFFER_ACCEPT == "Y"),
      n_refusals = n_offers - accept,
    ) %>% 
  group_by(LISTING_CTR_CODE) %>% 
    summarize(
      n_candidates = n_distinct(WL_ID_CODE),
      median_refusals = median(n_refusals),
      n_offers = sum(n_offers),
      n_refusals = sum(n_refusals),
      n_tx = sum(accept),
      p_tx = mean(accept)
    ) %>% 
  ungroup() 

refusals %>% print_table()
refusals %>% write_csv("data/refusals.csv")
# n_candidates: number of candidates listed at center
# median_refusals: median number of offer refusals per candidate
# n_{offers, refusals}: number of offers/refusals at center
# {n,p}_tx: number/proportion of candidates transplanted (at time of data collection)

```

## Plots

```{r}

#----------------------------------------------------------------------------#
## Plots ----
#----------------------------------------------------------------------------#
theme_set(theme_bw())

#: median time to offer vs. median number of refusals
full_join(waiting_time, refusals, by = "LISTING_CTR_CODE") %>% 
  filter(n_total > 20) %>% 
  ggplot(aes(median_wait_days, median_refusals)) + 
  geom_smooth(color = "black",  alpha = .20) + 
  geom_point(aes(size = n_candidates), alpha = .50, pch = 1)  + 
  scale_x_continuous(breaks = seq(0, 1000, by = 7)) + 
  scale_y_continuous(breaks = seq(0, 100, by = 2)) + 
  coord_cartesian(ylim = c(0, NA)) + 
  labs(
    x = "median time to first offer (in days)", 
    y = "median number of refusals per candidate",
    size = "# candidates"
  ) 

#: ECDF of time to first offer
waiting_time %>% 
  ggplot() + 
  stat_ecdf(aes(x = median_wait_days_1A, color = "1A")) + 
  stat_ecdf(aes(x = median_wait_days_1B, color = "1B")) + 
  stat_ecdf(aes(x = median_wait_days_2, color = "2")) + 
  scale_x_continuous(breaks = seq(0, 1000, by = 7)) + 
  scale_y_continuous(breaks = seq(0, 1, by = .10)) + 
  coord_cartesian(xlim = c(0, 50)) + 
  labs(
    x = "time to first offer (in days)", 
    y = "Cumulative Probability",
    color = "Status"
  )

  
#: center size vs. refusals
refusals %>% 
  filter(n_candidates > 20) %>% 
  ggplot(aes(n_candidates/10, median_refusals)) + 
  geom_smooth(color = "black",  alpha = .20) + 
  geom_point() + 
  scale_x_continuous(breaks = seq(0, 100, by = 2)) + 
  scale_y_continuous(breaks = seq(0, 100, by = 2)) + 
  labs(
    x = "avg number of candidates per year",
    y = "median number of refusals per candidate"
  )
  
#: center size vs. wait time
waiting_time %>% 
  filter(n_total > 20) %>% 
  ggplot(aes(n_total/10, median_wait_days)) + 
  geom_smooth(color = "black",  alpha = .20) + 
  geom_point() + 
  scale_x_continuous(breaks = seq(0, 100, by = 2)) + 
  scale_y_continuous(breaks = seq(0, 100, by = 10)) + 
  labs(
    x = "avg number of candidates per year",
    y = "median time until first offer (in days)"
  )


set.seed(321)
refusals %>% 
  filter(n_candidates > 20) %>% 
  ggplot(aes(median_refusals, p_tx)) + 
  geom_smooth(color = "black",  alpha = .20) + 
  geom_jitter(aes(size = n_candidates), alpha = .2, 
             width = .125, height=0) + 
  scale_x_continuous(breaks = seq(0, 1000, by = 1)) + 
  scale_y_continuous(breaks = seq(0, 1, by = .10)) + 
  labs(
    x = "median number of refusals per candidate",
    y = "proportion of candidates transplanted",
  )
   
```

