---
title: "Model Data and Train/Test split"
author: "Michael D. Porter"
date: "07/05/2024"
format:
  html:
    toc: true
    toc-depth: 5
    code-fold: false
    code-summary: "Show the code"
    df_print: paged
    embed-resources: true
    default-image-extension: svg
    dpi: 600
---

```{r load-libraries}
#| echo: true
#| warning: false
#| message: false
#| results: hide

library(tidymodels)
library(tidyverse)
```

```{r paths}
#| include: false

dir_data = "data"
dir_save = "data"
```


### Model Dataset

```{r load-dataset}
#| echo: true
#| warning: false
#| message: false
#| eval: true

model_data = read_rds(file.path(dir_data, "model_data.rds"))
model_data %>% str()
```

### Survival Model Dataset

Create train/test split. Use 1000 observations for testing and `r nrow(model_data) - 1000` for testing. Stratify on the `outcome`. 

```{r data-splitting}
library(tidymodels)

set.seed(2024)
n_test = 1000

split = model_data %>% 
  rsample::initial_split(
    prop = 1 - n_test/nrow(.), 
    strata = outcome
  )  

model_data_train = training(split)
model_data_test = testing(split)
```

```{r}
model_data_train %>% count(outcome) %>% mutate(p = n/sum(n))
model_data_test %>% count(outcome) %>% mutate(p = n/sum(n))
```


```{r}
model_data_train %>% write_rds(file.path(dir_data, "model_data_train.rds"))
model_data_test %>% write_rds(file.path(dir_data, "model_data_test.rds"))


model_data_index = 
  model_data %>% transmute(Row = row_number(), outcome, WL_ID_CODE) %>% 
  left_join(
    tidy(split), by = "Row"
  ) %>% 
  mutate(
    Data = case_match(Data, "Analysis" ~ "Train", "Assessment" ~ "Test")
  )

model_data_index %>% write_rds(file.path(dir_data, "model_data_index.rds"))
```